resources:
-   ../../deployments/elasticsearch.yml
-   ../../deployments/microservice-product-search-export.yml
-   ../../deployments/microservice-product-search.yml
-   ../../deployments/postgres.yml
-   ../../deployments/redis.yml
-   ../../deployments/smtp-server.yml
-   ../../deployments/webserver-php-fpm.yml
-   ../../services/elasticsearch.yml
-   ../../services/microservice-product-search-export.yml
-   ../../services/microservice-product-search.yml
-   ../../services/postgres.yml
-   ../../services/redis.yml
-   ../../services/smtp-server.yml
-   ../../services/webserver-php-fpm.yml
-   ../../ingress.yml
configMapGenerator:
    -   name: postgres-configuration
        files:
        -   ../../../docker/postgres/postgres.conf
    -   name: domains-urls
        files:
        -   ../../../app/config/domains_urls.yml
    -   name: parameters
        files:
        -   ../../../app/config/parameters.yml
