parameters:
  shopsys.admin_navigation.config_filepath: %shopsys.root_dir%/src/Shopsys/ShopBundle/Resources/config/admin_menu.yml
  shopsys.bestselling_product.cache_directory_path: %kernel.cache_dir%/bestselling_product
  shopsys.cron_config_filepath: %shopsys.root_dir%/src/Shopsys/ShopBundle/Resources/config/cron.yml
  shopsys.css_version_filepath: %shopsys.web_dir%/assets/cssVersion
  shopsys.data_fixtures.resource_customers_filepath: %shopsys.data_fixtures.resources_dir%/demo-data-customers.csv
  shopsys.data_fixtures.resource_products_filepath: %shopsys.data_fixtures.resources_dir%/demo-data-products.csv
  shopsys.data_fixtures.resources_dir: %shopsys.root_dir%/src/Shopsys/ShopBundle/DataFixtures/resources
  shopsys.default_db_schema_filepath: %shopsys.resources_dir%/database/schema.sql
  shopsys.demo_images_archive_url: https://images.shopsysdemo.com/demoImages.v9.zip
  shopsys.demo_images_dql_url: https://images.shopsysdemo.com/demoImagesSql.v7.sql
  shopsys.doctrine.metadata_cache_directory_path: %kernel.cache_dir%/doctrine_metadata
  shopsys.doctrine.query_cache_directory_path: %kernel.cache_dir%/doctrine_query
  shopsys.domain_config_filepath: %kernel.root_dir%/config/domains.yml
  shopsys.domain_images_dir: %shopsys.web_dir%%shopsys.domain_images_url_prefix%
  shopsys.domain_images_url_prefix: /content/admin/images/domain
  shopsys.domain_urls_config_filepath: %kernel.root_dir%/config/domains_urls.yml
  shopsys.error_pages_dir: %shopsys.root_dir%/var/errorPages/
  shopsys.feed_dir: %shopsys.web_dir%%shopsys.feed_url_prefix%
  shopsys.feed_url_prefix: /content/feeds/
  shopsys.filemanager_upload_dir: %shopsys.web_dir%/%shopsys.filemanager_upload_web_dir%
  shopsys.filemanager_upload_web_dir: content/wysiwyg
  shopsys.front_design_image_url_prefix: /assets/frontend/images/
  shopsys.heureka_category_feed_backup_filepath: %shopsys.resources_dir%/feeds/heureka-category-feed-backup.xml
  shopsys.heureka_category_feed_url: http://www.heureka.cz/direct/xml-export/shops/heureka-sekce.xml
  shopsys.image_config_filepath: %shopsys.root_dir%/src/Shopsys/ShopBundle/Resources/config/images.yml
  shopsys.image_dir: %shopsys.web_dir%%shopsys.image_url_prefix%
  shopsys.image_url_prefix: /content/images/
  shopsys.javascript_sources_dir: %shopsys.resources_dir%/scripts
  shopsys.javascript_url_prefix: /assets/scripts/
  shopsys.resources_dir: %shopsys.root_dir%/src/Shopsys/ShopBundle/Resources
  shopsys.root_dir: %kernel.root_dir%/..
  shopsys.sitemaps_dir: %shopsys.web_dir%%shopsys.sitemaps_url_prefix%
  shopsys.sitemaps_url_prefix: /content/sitemaps
  shopsys.styles_dir: src/Shopsys/ShopBundle/Resources/styles
  shopsys.uploaded_file_config_filepath: %shopsys.root_dir%/src/Shopsys/ShopBundle/Resources/config/uploaded_files.yml
  shopsys.uploaded_file_dir: %shopsys.web_dir%%shopsys.uploaded_file_url_prefix%
  shopsys.uploaded_file_url_prefix: /content/uploadedFiles/
  shopsys.web_dir: %shopsys.root_dir%/web