security:
  encoders:
    Symfony\Component\Security\Core\User\UserInterface:
      algorithm: bcrypt
      cost: 12

  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]

  providers:
    administrators:
      id: shopsys.shop.administrator.security.administrator_user_provider

    user_identities:
      id: shopsys.shop.customer.frontend_user_provider

  firewalls:
    # see Shopsys\ShopBundle\Model\Administrator\Security\AdministratorFrontSecurityFacade
    administration:
      pattern: ^/(admin/|efconnect|elfinder)
      anonymous: ~
      provider: administrators
      form_login:
        check_path: admin_login_check
        login_path: admin_login
        default_target_path: admin_default_dashboard
        use_referer: true
        username_parameter: "admin_login_form[username]"
        password_parameter: "admin_login_form[password]"
        csrf_parameter: "admin_login_form[_token]"
      logout:
        path: admin_logout
        success_handler: shopsys.shop.security.admin_logout_handler
        csrf_parameter: _csrf_token
        csrf_token_generator: form.csrf_provider
        csrf_token_id: admin_logout
        invalidate_session: false

    frontend:
      pattern: ^/
      anonymous: ~
      provider: user_identities
      form_login:
        check_path: front_login_check
        login_path: front_login
        username_parameter: "front_login_form[email]"
        password_parameter: "front_login_form[password]"
        csrf_parameter: "front_login_form[_token]"
        success_handler: shopsys.shop.security.customer_login_handler
        failure_handler: shopsys.shop.security.customer_login_handler
        remember_me: true
      remember_me:
        secret: "%secret%"
        lifetime: 2592000 # 30 days
        path: /
        domain: ~
        remember_me_parameter: "front_login_form[rememberMe]"
      logout:
        path: front_logout
        success_handler: shopsys.shop.security.front_logout_handler
        csrf_parameter: _csrf_token
        csrf_token_generator: form.csrf_provider
        csrf_token_id: frontend_logout
        invalidate_session: false

  access_control:
    # same pattern must be in routing_front.yml
    - { path: ^/login-as-remembered-user/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/superadmin/, roles: ROLE_SUPER_ADMIN }
    - { path: ^/admin/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/authorization/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, roles: ROLE_ADMIN }
    - { path: ^/efconnect, roles: ROLE_ADMIN }
    - { path: ^/elfinder, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
