# Example:
#-   name: product
#    class: Shopsys\FrameworkBundle\Model\Product\Product
#    types:
#        -   name: gallery
#            multiple: true
#            sizes:
#                -   name: detail
#                    width: 200
#                    height: 300
#                    crop: false
#                    occurrence: 'Front-end: Product detail, when selected'
#                    additionalSizes:
#                       - {width: 1100, height: ~, media: "(min-width: 1200px)"}
#                       - {width: 275, height: ~, media: "(max-width: 480px)"}
#                -   name: list
#                    width: 100
#                    height: 100
#                    crop: true
#                    occurrence: 'Front-end: Product detail'
#        -   name: main
#            sizes:
#                -   name: ~
#                    width: 200
#                    height: 300
#                    crop: false
#                    occurrence: 'Front-end: Product detail, Product list'

-   name: payment
    class: Shopsys\FrameworkBundle\Model\Payment\Payment
    sizes:
        -   name: ~
            width: ~
            height: 20
            crop: false
            occurrence: 'Front-end: Ordering process'

-   name: category
    class: Shopsys\FrameworkBundle\Model\Category\Category
    sizes:
        -   name: ~
            width: 30
            height: 30
            crop: false
            occurrence: 'Front-end: Product list by category'

-   name: product
    class: Shopsys\FrameworkBundle\Model\Product\Product
    multiple: true
    sizes:
        -   name: ~
            width: 410
            height: ~
            crop: false
            occurrence: 'Front-end: Main image in product detail'
            additionalSizes:
                - {width: 710, height: ~, media: "(min-width: 480px) and (max-width: 768px)"}
        -   name: galleryThumbnail
            width: ~
            height: 35
            crop: false
            occurrence: 'Front-end: Thumbnail of images under the main image in product detail'
        -   name: list
            width: 150
            height: ~
            crop: false
            occurrence: 'Front-end: Listing of products in section, listing of products on special offer'
        -   name: thumbnail
            width: 50
            height: 40
            crop: false
            occurrence: 'Front-end: Preview in autocomplete for search, preview in cart during ordering process'

-   name: sliderItem
    class: Shopsys\FrameworkBundle\Model\Slider\SliderItem
    sizes:
        -   name: ~
            width: 900
            height: 230
            crop: true
            occurrence: 'Front-end: Main page slider'
            additionalSizes:
                - {width: 730, height: 230, media: "(max-width: 1023px)"}

-   name: transport
    class: Shopsys\FrameworkBundle\Model\Transport\Transport
    sizes:
        -   name: ~
            width: ~
            height: 20
            crop: false
            occurrence: 'Front-end: Ordering process'

-   name: noticer
    class: Shopsys\FrameworkBundle\Model\Advert\Advert
    sizes:
        -   name: header
            width: 1160
            height: ~
            crop: false
            occurrence: 'Front-end: Advertising under heading'
            additionalSizes:
                - {width: 440, height: ~, media: "(max-width: 479px)"}
                - {width: 730, height: ~, media: "(max-width: 768px)"}
                - {width: 990, height: ~, media: "(max-width: 1023px)"}
        -   name: footer
            width: 1160
            height: ~
            crop: false
            occurrence: 'Front-end: Advertising above footer'
            additionalSizes:
                - {width: 440, height: ~, media: "(max-width: 479px)"}
                - {width: 730, height: ~, media: "(max-width: 768px)"}
                - {width: 990, height: ~, media: "(max-width: 1023px)"}
        -   name: productList
            width: 900
            height: ~
            crop: false
            occurrence: 'Front-end: Advertising in category (above the category name)'
            additionalSizes:
                - {width: 440, height: ~, media: "(max-width: 479px)"}
                - {width: 730, height: ~, media: "(max-width: 1023px)"}
        -   name: leftSidebar
            width: 240
            height: ~
            crop: false
            occurrence: 'Front-end: Advertising in the left panel under the category tree'
            additionalSizes:
                - {width: 440, height: ~, media: "(max-width: 479px)"}
                - {width: 730, height: ~, media: "(max-width: 768px)"}

-   name: brand
    class: Shopsys\FrameworkBundle\Model\Product\Brand\Brand
    sizes:
        -   name: ~
            width: 300
            height: 200
            crop: false
            occurrence: 'Front-end: Brand page'
