front_cart:
  path: /cart/
  defaults: { _controller: ShopsysShopBundle:Front\Cart:index }

front_customer_edit:
  path: /customer/edit/
  defaults: { _controller: ShopsysShopBundle:Front\Customer:edit }

front_customer_orders:
  path: /customer/orders/
  defaults: { _controller: ShopsysShopBundle:Front\Customer:orders }

front_customer_order_detail_registered:
  path: /customer/orders/detail/{orderNumber}
  defaults: { _controller: ShopsysShopBundle:Front\Customer:orderDetailRegistered }

front_customer_order_detail_unregistered:
  path: /order-detail/{urlHash}
  defaults: { _controller: ShopsysShopBundle:Front\Customer:orderDetailUnregistered }

front_login:
  path: /login/
  defaults: { _controller: ShopsysShopBundle:Front\Login:login }

front_logout:
  path: /logout/
  # controller's action is unnecessary, because firewall processes whole request

front_order_index:
  path: /order/
  defaults: { _controller: ShopsysShopBundle:Front\Order:index }

front_order_sent:
  path: /order-confirm/
  defaults: { _controller: ShopsysShopBundle:Front\Order:sent }

front_product_search:
  path: /search
  defaults: { _controller: ShopsysShopBundle:Front\Product:search }

front_registration_register:
  path: /registration/
  defaults: { _controller: ShopsysShopBundle:Front\Registration:register }

front_registration_reset_password:
  path: /forgotten-password/
  defaults: { _controller: ShopsysShopBundle:Front\CustomerPassword:resetPassword }

front_registration_set_new_password:
  path: /new-password/
  defaults: { _controller: ShopsysShopBundle:Front\CustomerPassword:setNewPassword }

front_brand_list:
  path: /brands-list/
  defaults: { _controller: ShopsysShopBundle:Front\Brand:list }

front_personal_data:
  path: /personal-information-overview/
  defaults: { _controller: ShopsysShopBundle:Front\PersonalData:index }

front_personal_data_access:
  path: /personal-information-overview/{email}/
  defaults: { _controller: ShopsysShopBundle:Front\PersonalData:access }
