fos_ck_editor:
    default_config: default
    configs:
        default:
            entities_greek: false
            entities_latin: false
            enterMode: 2
            shiftEnterMode: 1
            filebrowserBrowseRoute: elfinder
            toolbar:
                - ['Bold', 'Italic', 'Underline', 'Strike', 'Superscript', 'Subscript', '-', 'RemoveFormat']
                - ['PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                - ['Outdent', 'Indent', '-', 'Blockquote']
                - ['Link', 'Unlink']
                - '/'
                - ['Source', '-', 'Image', 'Flash', 'Table', 'SpecialChar', 'Iframe']
                - ['Format']
                - ['FontSize']
                - ['TextColor']

        email:
            entities_greek: false
            entities_latin: false
            enterMode: 2
            shiftEnterMode: 1
            filebrowserBrowseRoute: elfinder
            toolbar:
                - ['Bold', 'Italic', 'Underline', 'Strike', 'Superscript', 'Subscript', '-', 'RemoveFormat']
                - ['PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                - ['Outdent', 'Indent', '-', 'Blockquote']
                - ['Link', 'Unlink']
                - '/'
                - ['Source', '-', 'Image', 'SpecialChar']
                - ['Format']
                - ['FontSize']
                - ['TextColor']
