twig:
    debug: "%kernel.debug%"
    exception_controller: 'Shopsys\ShopBundle\Controller\Front\ErrorController::showAction'
    form_themes:
        - '@ShopsysFramework/Common/Form/theme.html.twig'
        - '@ShopsysFramework/Admin/Form/colorpickerFields.html.twig'
        - '@ShopsysFramework/Admin/Form/fileuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/imageuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/pricetableFields.html.twig'
        - '@ShopsysFramework/Admin/Form/orderItems.html.twig'
        - '@ShopsysFramework/Admin/Form/orderlistFields.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyCustomer.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyDomainIconFields.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyFields.html.twig'
        - '@ShopsysFramework/Admin/Form/warningMessage.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyUrl.html.twig'
        - '@ShopsysFramework/Admin/Form/localizedFullWidth.html.twig'
        - '@ShopsysFramework/Admin/Form/productParameterValue.html.twig'
        - '@ShopsysFramework/Admin/Form/productCalculatedPrices.html.twig'
    strict_variables: true
    globals:
        globalMultipleFormSetting: '@Shopsys\FrameworkBundle\Component\Form\MultipleFormSetting'
