- service: SS6\ShopBundle\Model\Pricing\Vat\VatDeletionCronModule
  time:
    hours: '*'
    minutes: '*'

- service: SS6\ShopBundle\Model\Product\Pricing\ProductPriceCronModule
  time:
    hours: '*'
    minutes: '*'

- service: SS6\ShopBundle\Model\Product\ProductVisibilityImmediateCronModule
  time:
    hours: '*'
    minutes: '*'

- service: SS6\ShopBundle\Model\Product\ProductVisibilityMidnightCronModule
  time:
    hours: '0'
    minutes: '0'

- service: SS6\ShopBundle\Model\Product\Availability\ProductAvailabilityCronModule
  time:
    hours: '*'
    minutes: '*'

- service: SS6\ShopBundle\Model\Feed\FeedCronModule
  time:
    hours: '*/6'
    minutes: '0'

- service: SS6\ShopBundle\Model\Feed\DeliveryFeedCronModule
  time:
    hours: '*'
    minutes: '10'

- service: SS6\ShopBundle\Component\Sitemap\SitemapCronModule
  time:
    hours: '4'
    minutes: '0'

- service: SS6\ShopBundle\Model\Feed\Category\FeedCategoryCronModule
  time:
    hours: '3'
    minutes: '0'

# This module should run as last because it creates multiple kernels and fake requests.
- service: SS6\ShopBundle\Component\Error\ErrorPageCronModule
  time:
    hours: '21'
    minutes: '10'