front_article_detail:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Article:detail }

front_product_detail:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Product:detail }

front_product_list:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Product:listByCategory }

front_brand_detail:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Product:listByBrand }
