front_cart:
  pattern: /cart/
  defaults: { _controller: SS6ShopBundle:Front\Cart:index }

front_customer_edit:
  pattern: /customer/edit/
  defaults: { _controller: SS6ShopBundle:Front\Customer:edit }

front_customer_orders:
  pattern: /customer/orders/
  defaults: { _controller: SS6ShopBundle:Front\Customer:orders }

front_customer_order_detail_registered:
  pattern: /customer/orders/detail/{orderNumber}
  defaults: { _controller: SS6ShopBundle:Front\Customer:orderDetailRegistered }

front_customer_order_detail_unregistered:
  pattern: /detail-objednavky/{urlHash}
  defaults: { _controller: SS6ShopBundle:Front\Customer:orderDetailUnregistered }

front_login:
  pattern: /login/
  defaults: { _controller: SS6ShopBundle:Front\Login:login }

front_logout:
  pattern: /logout/
  # controller's action is unnecessary, because firewall processes whole request

front_order_index:
  pattern: /order/
  defaults: { _controller: SS6ShopBundle:Front\Order:index }

front_order_sent:
  pattern: /order-confirm/
  defaults: { _controller: SS6ShopBundle:Front\Order:sent }

front_product_search:
  pattern: /search
  defaults: { _controller: SS6ShopBundle:Front\Product:search }

front_registration_register:
  pattern: /registration/
  defaults: { _controller: SS6ShopBundle:Front\Registration:register }

front_registration_reset_password:
  pattern: /forgotten-password/
  defaults: { _controller: SS6ShopBundle:Front\CustomerPassword:resetPassword }

front_registration_set_new_password:
  pattern: /new-password/
  defaults: { _controller: SS6ShopBundle:Front\CustomerPassword:setNewPassword }

front_brand_detail:
  pattern: /brand/{brandId}/
  defaults: { _controller: SS6ShopBundle:Front\Product:listByBrand }
  requirements:
    brandId: \d+

front_brand_list:
  pattern: /brands-list/
  defaults: { _controller: SS6ShopBundle:Front\Brand:list }
